Homework Mock
coders-school/pizzas pull request #13
Opened 2020-09-17 10:37 UTC by kari0036

2020-09-17 10:42 UTC, MaciejSalamonski approved these changes
Very nice 👍

2020-09-17 10:42 UTC, MaciejSalamonski commented on test/PizzeriaTest.cpp
> +    delete ps;
+1

2020-09-20 21:22 UTC, ziobron requested changes
Almost good. Only one change needed.

2020-09-20 21:22 UTC, ziobron commented on test/PizzeriaTest.cpp
> +    EXPECT_CALL(dt, sleep_for).Times(1);
```suggestion
    EXPECT_CALL(dt, sleep_for(ps.getBakingTime())).Times(1);
```

2020-09-20 21:22 UTC, ziobron commented on test/PizzeriaTest.cpp
> +    EXPECT_CALL(tm, sleep_for).Times(3);
```suggestion
    EXPECT_CALL(tm, sleep_for(ps.getBakingTime())).Times(1);
    EXPECT_CALL(tm, sleep_for(mock1BakingTime)).Times(1);
    EXPECT_CALL(tm, sleep_for(mock2BakingTime)).Times(1);
```

2020-09-21 17:39 UTC, WBigaj reviewed
I have checked your code and have nothing to add.

2020-09-22 17:48 UTC, ziobron approved these changes
Small changes needed (the code does not compile), but I accept it :)

2020-09-22 17:48 UTC, ziobron commented on test/PizzeriaTest.cpp
> +    EXPECT_CALL(dt, sleep_for(ps.getBakingTime())).Times(1);
```suggestion
    EXPECT_CALL(dt, sleep_for(ps->getBakingTime())).Times(1);
```
ps is a pointer. Sorry for my misleading tip, but CI detected that this code does not compile

2020-09-22 17:48 UTC, ziobron commented on test/PizzeriaTest.cpp
> +    EXPECT_CALL(tm, sleep_for(ps.getBakingTime())).Times(1);
```suggestion
    EXPECT_CALL(tm, sleep_for(ps->getBakingTime())).Times(1);
```

2020-09-22 17:49 UTC, ziobron commented
{ "requirement_ids" : [1119, 1119, 1119, 3524, 3525, 3526] }
3 * 3 XP za punktualność (1119)
10 XP za TimeMock w Pizzas (3524)
15 XP za nowy przypadek testowy w Pizzas (3525)
5 XP za workflow w Pizzas (3526)

2020-09-22 17:49 UTC, closed without merging